config/routes.rb
Rails.application.routes.draw do

  # Role Based Urls

  get 'dashboard/article_dashboard'

  get 'dashboard/audit_dashboard'

  get 'dashboard/ca_dashboard'

  get 'dashboard/manager_dashboard'

  # Authentication Urls

  devise_for :staffs, controllers: {
    sessions: 'staffs/sessions',
    registrations: 'staffs/registrations'
  }

  # Home Page

  get 'home/index'
  root 'home#index'
  
  # Resources

  resources :sub_tasks
  resources :tasks
  resources :client_types
  resources :clients

end

app/models/sub_task.rb
class SubTask < ApplicationRecord
  belongs_to :task, optional: true
  STATUS = ['DONE', 'PENDING']
end

app/controllers/sub_tasks_controller.rb
class SubTasksController < ApplicationController
  before_action :set_sub_task, only: [:show, :edit, :update, :destroy]

  # GET /sub_tasks
  # GET /sub_tasks.json
  def index
    @sub_tasks = SubTask.all
  end

  # GET /sub_tasks/1
  # GET /sub_tasks/1.json
  def show
  end

  # GET /sub_tasks/new
  def new
    @sub_task = SubTask.new
  end

  # GET /sub_tasks/1/edit
  def edit
  end

  # POST /sub_tasks
  # POST /sub_tasks.json
  def create
    @sub_task = SubTask.new(sub_task_params)

    respond_to do |format|
      if @sub_task.save
        format.html { redirect_to @sub_task, notice: 'Sub task was successfully created.' }
        format.json { render :show, status: :created, location: @sub_task }
      else
        format.html { render :new }
        format.json { render json: @sub_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_tasks/1
  # PATCH/PUT /sub_tasks/1.json
  def update
    respond_to do |format|
      if @sub_task.update(sub_task_params)
        format.html { redirect_to @sub_task, notice: 'Sub task was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_task }
      else
        format.html { render :edit }
        format.json { render json: @sub_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_tasks/1
  # DELETE /sub_tasks/1.json
  def destroy
    @sub_task.destroy
    respond_to do |format|
      format.html { redirect_to sub_tasks_url, notice: 'Sub task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_task
      @sub_task = SubTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_task_params
      params.require(:sub_task).permit(:status, :title, :completion_date, :task_id)
    end
end

app/views/sub_tasks/_form.html.erb
<%= form_for @sub_task, :html => { :class => "form-horizontal sub_task" } do |f| %>

  <% if @sub_task.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@sub_task.errors.count, "error") %> prohibited this sub_task from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @sub_task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select :status, SubTask::STATUS, :to_s, :upcase, {}, {class: "form-control"} %>
    </div>
    <%=f.error_span(:status) %>
  </div>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :completion_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10" id= "datePicker3">
      <%= f.text_field :completion_date, :class => 'form-control', id: "completion_date"  %>
      <span class="input-group-addon input-date">
        <span class="fa fa-calendar"></span>
      </span>
    </div>
    <%=f.error_span(:completion_date) %>
  </div>
  <div class="form-group">
    <%= f.label :task_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :task_id, options_for_select(Task.all.collect {|task| [ task.nature_of_task, task.id ] },(f.object.try(:task_id))),{prompt: 'Select A Task'}, { :class => 'form-control'} %>
    </div>
    <%=f.error_span(:task_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-success' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sub_tasks_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/sub_tasks/edit.html.erb
<%- model_class = SubTask -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sub_tasks/index.html.erb
<%- model_class = SubTask -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:completion_date) %></th>
      <th><%= model_class.human_attribute_name(:task_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sub_tasks.each do |sub_task| %>
      <tr>
        <td><%= link_to sub_task.id, sub_task_path(sub_task) %></td>
        <td><%= sub_task.status %></td>
        <td><%= sub_task.title %></td>
        <td><%= sub_task.completion_date %></td>
        <td><%= sub_task.task_id %></td>
        <td><%=l sub_task.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      sub_task_path(sub_task), :class => 'btn btn-info btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sub_task_path(sub_task), :class => 'btn btn-warning btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sub_task_path(sub_task),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sub_task_path,
            :class => 'btn btn-primary' %>

app/views/sub_tasks/new.html.erb
<%- model_class = SubTask -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sub_tasks/show.html.erb
<%- model_class = SubTask -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @sub_task.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @sub_task.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:completion_date) %>:</strong></dt>
  <dd><%= @sub_task.completion_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:task_id) %>:</strong></dt>
  <dd><%= @sub_task.task_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              sub_tasks_path, :class => 'btn btn-info'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sub_task_path(@sub_task), :class => 'btn btn-warning' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sub_task_path(@sub_task),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>