config/routes.rb
Rails.application.routes.draw do

  # Role Based Urls

  get 'dashboard/article_dashboard'

  get 'dashboard/audit_dashboard'

  get 'dashboard/ca_dashboard'

  get 'dashboard/manager_dashboard'

  # Authentication Urls

  devise_for :staffs, controllers: {
    sessions: 'staffs/sessions',
    registrations: 'staffs/registrations'
  }

  # Home Page

  get 'home/index'
  root 'home#index'
  
  # Resources

  resources :sub_tasks
  resources :tasks
  resources :client_types
  resources :clients

end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :client_type, optional: true
  mount_uploader :profile_pic, ImageUploader
end

app/models/client_type.rb
class ClientType < ApplicationRecord
  has_many :clients, dependent: :destroy
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :contact_number, :firm_name, :email, :profile_pic, :client_type_id)
    end
end

app/views/clients/_form.html.erb
<%= form_for @client, :html => { :class => "form-horizontal client" } do |f| %>

  <% if @client.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @client.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :first_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:first_name) %>
  </div>
  <div class="form-group">
    <%= f.label :last_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :last_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:last_name) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_number, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact_number, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_number) %>
  </div>
  <div class="form-group">
    <%= f.label :firm_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :firm_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:firm_name) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :client_type_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :client_type_id, options_for_select(ClientType.all.collect {|ct| [ ct.name, ct.id ] },(f.object.try(:client_type_id))),{prompt: 'Select A Client Type'}, { :class => 'form-control'} %>
    </div>
    <%=f.error_span(:client_type_id) %>
  </div>
  <div class="form-group">
    <%= f.label :Profile_pic, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :profile_pic, :class => 'form-control' %>
    </div>
    <%=f.error_span(:profile_pic) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-success' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                clients_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/clients/edit.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clients/index.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:contact_number) %></th>
      <th><%= model_class.human_attribute_name(:firm_name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:client_type_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= link_to client.id, client_path(client) %></td>
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.contact_number %></td>
        <td><%= client.firm_name %></td>
        <td><%= client.email %></td>
        <td><%= client.client_type_id %></td>
        <td><%=l client.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      client_path(client), :class => 'btn btn-info btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_client_path(client), :class => 'btn btn-warning btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      client_path(client),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_client_path,
            :class => 'btn btn-primary' %>

app/views/clients/new.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clients/show.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Profile Pic</strong></dt>
  <dd class="client_pic">
    <%= image_tag @client.profile_pic_url %>
  </dd>
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @client.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @client.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_number) %>:</strong></dt>
  <dd><%= @client.contact_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:firm_name) %>:</strong></dt>
  <dd><%= @client.firm_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @client.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:client_type_id) %>:</strong></dt>
  <dd><%= @client.client_type_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
clients_path, :class => 'btn btn-info'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
edit_client_path(@client), :class => 'btn btn-warning' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
client_path(@client),
:method => 'delete',
:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
:class => 'btn btn-danger' %>