config/routes.rb
Rails.application.routes.draw do

  # Role Based Urls

  get 'dashboard/article_dashboard'

  get 'dashboard/audit_dashboard'

  get 'dashboard/ca_dashboard'

  get 'dashboard/manager_dashboard'

  # Authentication Urls

  devise_for :staffs, controllers: {
    sessions: 'staffs/sessions',
    registrations: 'staffs/registrations'
  }

  # Home Page

  get 'home/index'
  root 'home#index'
  
  # Resources

  resources :sub_tasks
  resources :tasks
  resources :client_types
  resources :clients

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">CaTask</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Client", clients_path  %></li>
        <li><%= link_to "Client Type", client_types_path  %></li>
        <li><%= link_to "Task", tasks_path  %></li>
        <li><%= link_to "Sub Task", sub_tasks_path  %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if staff_signed_in? %>
          <li><%= link_to "Sign Out", destroy_staff_session_path, method: :delete  %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_staff_registration_path  %></li>
          <li><%= link_to "Sign In", new_staff_session_path  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CaTask" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/header'%>

    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>

  </body>
</html>